export const FETCHING_DATA = 'FETCHING_DATA'
export const FETCHING_DATA_SUCCESS = 'FETCHING_DATA_SUCCESS'
export const FETCHING_DATA_FAILURE = 'FETCHING_DATA_FAILURE'
export const FETCHING_DATA_PROGRESS = 'FETCHING_DATA_PROGRESS'

export const SET_TEXT_GETTING = 'SET_TEXT_GETTING'
export const SET_TEXT_SUCCESS = 'SET_TEXT_SUCCESS'